---
:project:
  :use_exceptions: false
  :use_test_preprocessor: true
  :use_auxiliary_dependencies: true
  :build_root: build
  :test_file_prefix: test_
:environment: 
:extension:
  :executable: ".out"
:paths:
  :test:
  - "+:test/**"
  - "-:test/support"
  - "-:test/datareplay"
  :source:
  - src/**
  :support:
  - test/support
:defines:
  :commmon: &1 []
  :test:
  - *1
  - TEST
  :test_preprocess:
  - *1
  - TEST
:cmock:
  :mock_prefix: mock_
  :when_no_prototypes: :warn
  :enforce_strict_ordering: true
  :plugins:
  - :ignore
  - :callback
  :treat_as:
    uint8: HEX8
    uint16: HEX16
    uint32: UINT32
    int8: INT8
    bool: UINT8
:tools:
  :test_includes_preprocessor:
    :executable: gcc
    :arguments:
    - "-E"
    - "-MM"
    - "-MG"
    - "-I\"$\"": COLLECTION_PATHS_TEST_SUPPORT_SOURCE_INCLUDE_VENDOR
    - "-I\"$\"": COLLECTION_PATHS_TEST_TOOLCHAIN_INCLUDE
    - "-D\"$\"": COLLECTION_DEFINES_TEST_AND_VENDOR
    - "-D\"$\"": DEFINES_TEST_PREPROCESS
    - "-DGNU_COMPILER"
    - "-w"
    - "-nostdinc"
    - "${1}"
  :test_compiler:
    :executable: mpicc
    :name: mpi_test_compiler
    :arguments:
    - "-I\"$\"": COLLECTION_PATHS_TEST_SUPPORT_SOURCE_INCLUDE_VENDOR
    - "-I\"$\"": COLLECTION_PATHS_TEST_TOOLCHAIN_INCLUDE
    - "-D$": COLLECTION_DEFINES_TEST_AND_VENDOR
    - "-DGNU_COMPILER"
    - "-c ${1}"
    - "-o ${2}"
  :test_linker:
    :executable: mpicc
    :name: mpi_test_linker
    :arguments:
    - "-I/usr/local/include"
    - "-L/usr/local/lib"
    - "${1}"
    - "-o ${2}"
    - "-lmpispec"
  :test_fixture:
    :executable: mpirun
    :name: mpi_test_fixture
    :arguments:
    - "-np 1"
    - "${1}"
:plugins:
  :load_paths:
  - vendor/bundle/ruby/2.1.0/gems/ceedling-0.13.0/plugins
  :enabled:
  - stdout_pretty_tests_report
  - module_generator
