
# Time-stamp: <2007-11-14 22:30:43 shinya>

include /usr/local/share/mpispec/Makefile.test

CC = mpicc

ARGV = -np 3

SRC = src/cpi.c \
      src/integral.c

SPECSRC = spec/cpi_spec.c \
          spec/integral_spec.c \
          spec/mpiassertion_spec.c \
          spec/main_spec.c
