include ../share/Makefile.test

CC = mpicc

ARGV = -np 3

SRC = src/async.c \
      src/cpi.c \
      src/integral.c

SPECSRC = spec/main_spec.c \
          spec/async_spec.c \
          spec/cpi_spec.c \
          spec/fabs_spec.c \
          spec/integral_spec.c \
          spec/strcmp_spec.c

