
# Time-stamp: <2007-11-14 22:30:43 shinya>

include /usr/local/share/mpiunit/Makefile.test

CC = mpicc

ARGV = -np 3

SRC = src/cpi.c \
      src/integral.c

TESTSRC = test/test_cpi.c \
          test/test_integral.c \
          test/test_mpiassertion.c \
          test/test_main.c
