
# Time-stamp: <2007-11-14 22:32:31 shinya>

INSTDIR = /usr/local
CC=mpicc
MPISPECFLAGS = -I${INSTDIR}/include
MPISPECLIBS = -L${INSTDIR}/lib -lmpispec -lm
RUNTEST = run-test

mpispec:
	@${CC} ${MPISPECFLAGS} ${SRC} ${SPECRC} -o ${RUNTEST} ${MPISPECLIBS}
	@mpirun ${ARGV} ./${RUNTEST}
