#!/bin/sh

# Time-stamp: <2007-11-14 22:32:05 shinya>

INSTDIR=/usr/local
CC="mpicc"
EXEC="exec_test"
MPIUTFLAGS="-I${INSTDIR}/include -finstrument-functions -rdynamic"
MPIUTLIBS="-L${INSTDIR}/lib -lmpiunit -lm"

$CC $MPIUTFLAGS $MPIUTLIBS src/*.c test/*.c -o $EXEC
mpirun $* ./$EXEC
rm -f *.o $EXEC
